tap "cj-bc/cj-bc"
tap "d12frosted/emacs-plus"
tap "eddieantonio/eddieantonio"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "joshuaclayton/formulae"
tap "knqyf263/pet"
tap "knqyf263/trivy"
tap "neovim/neovim"
tap "rcmdnk/file"
tap "sanemat/font"
tap "universal-ctags/universal-ctags"
brew "readline", link: true
brew "python@3.8"
brew "ansible"
brew "ant"
brew "apr"
brew "apr-util"
brew "atk"
brew "atool"
brew "automake"
brew "bat"
brew "c-ares"
brew "ccat"
brew "cmatrix"
brew "cmigemo"
brew "composer"
brew "coreutils"
brew "cowsay"
brew "curl"
brew "libev"
brew "openldap"
brew "curl-openssl"
brew "zeromq"
brew "czmq"
brew "dbus"
brew "direnv"
brew "elasticsearch"
brew "embulk"
brew "emojify"
brew "exa"
brew "imlib2"
brew "feh"
brew "gmp"
brew "nettle"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "ffmpeg"
brew "figlet"
brew "fish"
brew "pango"
brew "fontforge"
brew "fortune"
brew "fswatch"
brew "fzf", args: ["HEAD"]
brew "gawk"
brew "gdk-pixbuf"
brew "geoip"
brew "ghostscript"
brew "ghq"
brew "git"
brew "git-delta"
brew "global", link: false
brew "go"
brew "googler"
brew "gradle"
brew "graphicsmagick"
brew "groovy"
brew "hicolor-icon-theme"
brew "gtk+"
brew "highlight"
brew "htop"
brew "hub"
brew "shared-mime-info"
brew "imagemagick"
brew "jo"
brew "oniguruma"
brew "jq"
brew "jsonpp"
brew "kind"
brew "kubernetes-cli"
brew "kubectx"
brew "kubeseal"
brew "libcaca"
brew "libgcrypt"
brew "libiconv"
brew "libksba"
brew "libpq"
brew "libsodium"
brew "libxml2"
brew "mas"
brew "mysql", restart_service: true
brew "navi"
brew "neofetch"
brew "neovim"
brew "nnn"
brew "node"
brew "node-build"
brew "peco"
brew "php"
brew "postgresql"
brew "python@2", link: false
brew "ranger"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "ruby-build"
brew "sphinx-doc"
brew "starship"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "up"
brew "urlview"
brew "utf8proc"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "eddieantonio/eddieantonio/imgcat"
brew "jesseduffield/lazygit/lazygit"
brew "rcmdnk/file/brew-file"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "docker"
cask "alfred"
cask "edex-ui"
cask "alacritty"
cask "blackhole"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "google-japanese-ime"
cask "firefox"
cask "flux"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "kitty"
cask "licecap"
cask "sequel-pro-nightly"
cask "skype"
cask "shiftit"
cask "spotify"
cask "sublime-text"
cask "td-agent"
cask "visual-studio-code"
cask "wireshark-chmodbpf"
cask "xquartz"
mas "Evernote", id: 406056744
mas "Keynote", id: 409183694
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Pages", id: 409201541
mas "PDF to Excel by Flyingbee", id: 1018762334
mas "PicGIF Lite", id: 844918735
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "The Unarchiver", id: 425424353
mas "Total Video Converter Lite", id: 520374433
